-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: SGFComm

local flatbuffers = require('flatbuffers')

local CL_GS_Login = {} -- the module
local CL_GS_Login_mt = {} -- the class metatable

function CL_GS_Login.New()
    local o = {}
    setmetatable(o, {__index = CL_GS_Login_mt})
    return o
end
function CL_GS_Login.GetRootAsCL_GS_Login(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = CL_GS_Login.New()
    o:Init(buf, n + offset)
    return o
end
function CL_GS_Login_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function CL_GS_Login_mt:Token()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function CL_GS_Login.Start(builder) builder:StartObject(1) end
function CL_GS_Login.AddToken(builder, token) builder:PrependUOffsetTRelativeSlot(0, token, 0) end
function CL_GS_Login.End(builder) return builder:EndObject() end

return CL_GS_Login -- return the module