-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: SGFComm

local flatbuffers = require('flatbuffers')

local LS_CL_ServerList = {} -- the module
local LS_CL_ServerList_mt = {} -- the class metatable

function LS_CL_ServerList.New()
    local o = {}
    setmetatable(o, {__index = LS_CL_ServerList_mt})
    return o
end
function LS_CL_ServerList.GetRootAsLS_CL_ServerList(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = LS_CL_ServerList.New()
    o:Init(buf, n + offset)
    return o
end
function LS_CL_ServerList_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function LS_CL_ServerList_mt:Servers(j)
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('SGFComm.Server').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function LS_CL_ServerList_mt:ServersLength()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function LS_CL_ServerList.Start(builder) builder:StartObject(1) end
function LS_CL_ServerList.AddServers(builder, Servers) builder:PrependUOffsetTRelativeSlot(0, Servers, 0) end
function LS_CL_ServerList.StartServersVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function LS_CL_ServerList.End(builder) return builder:EndObject() end

return LS_CL_ServerList -- return the module