-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: SGFComm

-- ////////////////////////////// server list /////////////////
local ServerStatus = {
    Normal = 1,
    Close = 2,
    Busy = 3,
    Msaintenance = 4,
}

return ServerStatus -- return the module